import DataCenterSocialContract

#print axioms ComputeDividend.minimal_no_harm_transfer_is_pointwise_least
#print axioms ComputeDividend.minimal_no_harm_transfer_base_plus_topup
#print axioms ComputeDividend.hybrid_cash_feasible_iff_minimal_cost_funded
#print axioms ComputeDividend.gross_rent_threshold_supports_hybrid_no_harm_cost
#print axioms ComputeDividend.monotone_utility_weakly_improves_under_modeled_no_harm
#print axioms ComputeDividend.joint_cash_compute_feasible_iff_separate_thresholds
#print axioms ComputeDividend.data_center_admission_implies_every_obligation
